/* eslint-disable react-refresh/only-export-components */
import { CheckCircle2, ChevronRight, Copy, FileText, Search, ShieldCheck } from 'lucide-react'
import { Link } from 'react-router-dom'
export const statusTone=s=>({AUTHENTIC:'success',VERIFIED:'success',SELECTED:'success',SHORTLISTED:'violet',INTERVIEW:'violet',UNDER_REVIEW:'warning',APPLIED:'info',REJECTED:'danger',PENDING:'warning'}[String(s).replaceAll(' ','_').toUpperCase()]||'info')
export function StatusBadge({children}){return <span className={`status-badge ${statusTone(children)}`}>{String(children).replaceAll('_',' ')}</span>}
export function PageHeader({eyebrow,title,description,action}){return <header className="page-header"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{description&&<p>{description}</p>}</div>{action}</header>}
export function StatCard({label,value,detail,icon:Icon}){return <article className="stat-card"><div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>{Icon&&<i><Icon size={20}/></i>}</article>}
export function EmptyState({title='Nothing here yet',message='New updates will appear here when they are available.'}){return <div className="empty-state"><FileText size={30}/><h3>{title}</h3><p>{message}</p></div>}
export function SectionCard({title,children,action}){return <section className="section-card"><div className="section-head"><h2>{title}</h2>{action}</div>{children}</section>}
export function SearchField({placeholder='Search'}){return <label className="search-field"><Search size={17}/><input aria-label={placeholder} placeholder={placeholder}/></label>}
export function InternshipCard({item}){return <article className="internship-card"><div className="card-line"><span className="company-mark">{item.company.slice(0,1)}</span><span className="verified"><ShieldCheck size={14}/> Verified company</span></div><div><h3>{item.title}</h3><p>{item.company} · {item.location} · {item.mode}</p></div><div className="internship-meta"><span>{item.duration}</span><strong>{item.stipend}</strong><b>{item.match}% Match</b></div><div className="chips">{item.skills.map(s=><span key={s}>{s}</span>)}</div><Link className="text-link" to={`/student/internships/${item.id}`}>View internship <ChevronRight size={16}/></Link></article>}
export function IdentityCard(){const copy=()=>navigator.clipboard?.writeText('SVKM-DS-2026-0042');return <article className="identity-card"><div className="identity-top"><span><ShieldCheck size={18}/> VERIFIED STUDENT</span><button aria-label="Copy Student ID" onClick={copy}><Copy size={16}/> Copy ID</button></div><strong>SVKM-DS-2026-0042</strong><h2>Som Chitte</h2><p>B.Tech Data Science · 3rd Year</p><div><span><CheckCircle2 size={15}/> Identity verified</span><span><CheckCircle2 size={15}/> Academic profile verified</span></div><Link to="/student/profile">View full profile <ChevronRight size={16}/></Link></article>}
