import { Router } from 'express'
import { z } from 'zod'
import { db } from '../database.js'
import { authenticate, authorize } from '../middleware/authenticate.js'
const router=Router(); router.use(authenticate,authorize('ADMIN')); const id=z.coerce.number().int().positive(); const internshipStatus=z.object({status:z.enum(['PUBLISHED','REJECTED','PENDING_APPROVAL'])});
router.get('/dashboard',(req,res)=>{const count=(sql)=>db.prepare(sql).get().count;res.json({counts:{students:count("SELECT COUNT(*) count FROM users WHERE role='STUDENT'"),industries:count("SELECT COUNT(*) count FROM users WHERE role='INDUSTRY'"),internships:count('SELECT COUNT(*) count FROM internships'),pendingInternships:count("SELECT COUNT(*) count FROM internships WHERE status='PENDING_APPROVAL'"),applications:count('SELECT COUNT(*) count FROM applications')}})});
router.get('/students',(req,res)=>res.json({students:db.prepare("SELECT u.id,u.name,u.email,u.is_active,sp.student_id,sp.college_name,sp.course,sp.graduation_year FROM users u JOIN student_profiles sp ON sp.user_id=u.id WHERE u.role='STUDENT' ORDER BY u.created_at DESC").all()}));
router.get('/industries',(req,res)=>res.json({industries:db.prepare("SELECT u.id,u.name,u.email,u.is_active,ip.company_name,ip.location,ip.is_verified FROM users u JOIN industry_profiles ip ON ip.user_id=u.id WHERE u.role='INDUSTRY' ORDER BY u.created_at DESC").all()}));
router.get('/internships',(req,res)=>res.json({internships:db.prepare('SELECT i.*,ip.company_name FROM internships i JOIN industry_profiles ip ON ip.id=i.industry_id ORDER BY i.created_at DESC').all()}));
router.get('/applications',(req,res)=>res.json({applications:db.prepare('SELECT a.*,i.title,u.name student_name,ip.company_name FROM applications a JOIN internships i ON i.id=a.internship_id JOIN student_profiles sp ON sp.id=a.student_id JOIN users u ON u.id=sp.user_id JOIN industry_profiles ip ON ip.id=i.industry_id ORDER BY a.applied_at DESC').all()}));
router.patch('/internships/:internshipId/status',(req,res,next)=>{try{const status=internshipStatus.parse(req.body).status,target=id.parse(req.params.internshipId);const r=db.prepare('UPDATE internships SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(status,target);if(!r.changes)return res.status(404).json({message:'Internship not found.'});db.prepare('INSERT INTO moderation_actions (admin_user_id,target_type,target_id,action) VALUES (?,?,?,?)').run(req.user.id,'INTERNSHIP',target,status);res.json({message:'Internship moderation updated.'})}catch(e){next(e)}});
router.patch('/users/:userId/active',(req,res,next)=>{try{const active=z.object({isActive:z.boolean()}).parse(req.body).isActive,target=id.parse(req.params.userId);const r=db.prepare("UPDATE users SET is_active=? WHERE id=? AND role!='ADMIN'").run(active?1:0,target);if(!r.changes)return res.status(404).json({message:'User not found.'});db.prepare('INSERT INTO moderation_actions (admin_user_id,target_type,target_id,action) VALUES (?,?,?,?)').run(req.user.id,'USER',target,active?'ACTIVATED':'DEACTIVATED');res.json({message:'User moderation updated.'})}catch(e){next(e)}}); export default router
