import { Router } from 'express'
import { z } from 'zod'
import { prisma } from '../lib/prisma.js'
import { authenticate, authorize } from '../middleware/authenticate.js'

const router = Router(); router.use(authenticate, authorize('FACULTY'))
const id = z.coerce.number().int().positive()
const placementSchema = z.object({ studentId: z.string().trim().min(3).max(50), companyName: z.string().trim().min(2).max(150), roleTitle: z.string().trim().min(2).max(150), placementDate: z.string().datetime().nullable().optional(), notes: z.string().trim().max(2000).optional().default('') })

router.get('/students', async (req, res, next) => { try { const input = z.object({ studentId: z.string().trim().min(3).optional(), search: z.string().trim().max(100).optional() }).parse(req.query); const students = await prisma.studentProfile.findMany({ where: { AND: [input.studentId ? { studentId: input.studentId } : {}, input.search ? { OR: [{ studentId: { contains: input.search, mode: 'insensitive' } }, { user: { name: { contains: input.search, mode: 'insensitive' } } }] } : {}] }, include: { user: true }, take: 100, orderBy: { studentId: 'asc' } }); res.json({ students: students.map((s) => ({ studentId: s.studentId, name: s.user.name, email: s.user.email, collegeName: s.collegeName, course: s.course, graduationYear: s.graduationYear })) }) } catch (error) { next(error) } })
router.get('/students/:studentId', async (req, res, next) => { try { const student = await prisma.studentProfile.findUnique({ where: { studentId: req.params.studentId }, include: { user: true, academicRecords: true, skills: true, applications: { include: { internship: { include: { company: true } }, progressUpdates: { orderBy: { recordedAt: 'desc' } }, certificate: true } }, placementRecords: true } }); if (!student) return res.status(404).json({ message: 'Student not found.' }); res.json({ student }) } catch (error) { next(error) } })
router.get('/applications/:applicationId/progress', async (req, res, next) => { try { const application = await prisma.application.findUnique({ where: { id: id.parse(req.params.applicationId) }, include: { progressUpdates: { orderBy: { recordedAt: 'desc' } } } }); if (!application) return res.status(404).json({ message: 'Application not found.' }); res.json({ progress: application.progressUpdates }) } catch (error) { next(error) } })
router.get('/certificates/:code', async (req, res, next) => { try { const certificate = await prisma.certificate.findUnique({ where: { certificateCode: req.params.code }, include: { application: { include: { student: { include: { user: true } }, internship: { include: { company: true } } } } } }); if (!certificate) return res.status(404).json({ message: 'Certificate not found.' }); res.json({ certificate }) } catch (error) { next(error) } })
router.patch('/certificates/:code/status', async (req, res, next) => { try { const status = z.object({ status: z.enum(['VALID', 'INVALID']) }).parse(req.body).status; const certificate = await prisma.certificate.update({ where: { certificateCode: req.params.code }, data: { status } }); res.json({ message: 'Certificate status updated.', certificate }) } catch (error) { next(error) } })
router.patch('/companies/:companyId/verification', async (req, res, next) => { try { const input = z.object({ isVerified: z.boolean(), isSuspicious: z.boolean().optional() }).parse(req.body); const updated = await prisma.companyProfile.update({ where: { id: id.parse(req.params.companyId) }, data: input }); res.json({ message: 'Company verification updated.', company: updated }) } catch (error) { next(error) } })
router.post('/placements', async (req, res, next) => { try { const input = placementSchema.parse(req.body); const student = await prisma.studentProfile.findUnique({ where: { studentId: input.studentId } }); if (!student) return res.status(404).json({ message: 'Student not found.' }); const record = await prisma.placementRecord.create({ data: { studentId: student.id, companyName: input.companyName, roleTitle: input.roleTitle, placementDate: input.placementDate ? new Date(input.placementDate) : null, notes: input.notes, recordedByUserId: req.user.id } }); res.status(201).json({ placement: record }) } catch (error) { next(error) } })
router.get('/analytics', async (req, res, next) => { try { const [students, companies, verifiedCompanies, openInternships, applications, completedInternships, certificates] = await prisma.$transaction([prisma.studentProfile.count(), prisma.companyProfile.count(), prisma.companyProfile.count({ where: { isVerified: true } }), prisma.internship.count({ where: { status: 'OPEN' } }), prisma.application.count(), prisma.application.count({ where: { completionStatus: 'COMPLETED' } }), prisma.certificate.count({ where: { status: 'VALID' } })]); res.json({ counts: { students, companies, verifiedCompanies, openInternships, applications, completedInternships, certificates } }) } catch (error) { next(error) } })

export default router
