import { Router } from 'express'
import { z } from 'zod'
import { db } from '../database.js'
import { authenticate, authorize } from '../middleware/authenticate.js'

const router = Router()
router.use(authenticate, authorize('INDUSTRY'))
const id = z.coerce.number().int().positive()
const profileSchema = z.object({ companyName: z.string().trim().min(2).max(150).optional(), website: z.string().trim().url().max(2048).nullable().optional(), location: z.string().trim().max(150).nullable().optional(), description: z.string().trim().max(2000).optional() }).refine((v) => Object.keys(v).length, 'Provide a field to update.')
const internshipSchema = z.object({ title: z.string().trim().min(3).max(150), description: z.string().trim().min(20).max(5000), location: z.string().trim().min(2).max(150), workMode: z.enum(['REMOTE', 'ONSITE', 'HYBRID']), durationWeeks: z.coerce.number().int().min(1).max(104), stipend: z.coerce.number().int().min(0).max(10000000).nullable().optional(), skills: z.string().trim().max(1000).optional().default(''), eligibilityCriteria: z.string().trim().max(3000).optional().default(''), applicationDeadline: z.string().date().nullable().optional(), status: z.enum(['DRAFT', 'PENDING_APPROVAL']).optional().default('PENDING_APPROVAL') })
const statusSchema = z.object({ status: z.enum(['PENDING', 'SHORTLISTED', 'REJECTED', 'SELECTED']) })
const interviewSchema=z.object({interviewAt:z.string().datetime().nullable().optional(),interviewNotes:z.string().trim().max(3000).optional().default('')})
const offerSchema=z.object({offerDetails:z.string().trim().min(3).max(3000)})
const completionSchema=z.object({completionStatus:z.enum(['IN_PROGRESS','COMPLETED'])})
const profile = (userId) => db.prepare('SELECT * FROM industry_profiles WHERE user_id=?').get(userId)
const internship = (row) => ({ id: row.id, title: row.title, description: row.description, location: row.location, workMode: row.work_mode, durationWeeks: row.duration_weeks, stipend: row.stipend, skills: row.skills, eligibilityCriteria:row.eligibility_criteria, applicationDeadline: row.application_deadline, status: row.status, createdAt: row.created_at })

router.get('/profile', (req, res) => { const p = profile(req.user.id); res.json({ profile: { companyName:p.company_name, website:p.website, location:p.location, description:p.description, isVerified:!!p.is_verified } }) })
router.patch('/profile', (req,res,next) => { try { const input=profileSchema.parse(req.body); const p=profile(req.user.id); const fields={company_name:input.companyName,website:input.website,location:input.location,description:input.description}; const entries=Object.entries(fields).filter(([,v])=>v!==undefined); db.prepare(`UPDATE industry_profiles SET ${entries.map(([k])=>`${k}=?`).join(', ')}, updated_at=CURRENT_TIMESTAMP WHERE id=?`).run(...entries.map(([,v])=>v),p.id); res.json({message:'Company profile updated.'}) } catch(e){next(e)} })
router.post('/internships', (req,res,next) => { try { const input=internshipSchema.parse(req.body); const p=profile(req.user.id); const r=db.prepare('INSERT INTO internships (industry_id,title,description,location,work_mode,duration_weeks,stipend,skills,eligibility_criteria,application_deadline,status) VALUES (?,?,?,?,?,?,?,?,?,?,?)').run(p.id,input.title,input.description,input.location,input.workMode,input.durationWeeks,input.stipend??null,input.skills,input.eligibilityCriteria,input.applicationDeadline??null,input.status); res.status(201).json({message: input.status==='DRAFT'?'Draft saved.':'Internship submitted for approval.', internship:{id:Number(r.lastInsertRowid),...input}}) } catch(e){next(e)} })
router.get('/internships', (req,res) => { const p=profile(req.user.id); const rows=db.prepare('SELECT * FROM internships WHERE industry_id=? ORDER BY created_at DESC').all(p.id); res.json({internships:rows.map(internship)}) })
router.patch('/internships/:internshipId', (req,res,next) => { try { const internshipId=id.parse(req.params.internshipId); const input=internshipSchema.parse(req.body); const p=profile(req.user.id); const found=db.prepare('SELECT id FROM internships WHERE id=? AND industry_id=?').get(internshipId,p.id); if(!found)return res.status(404).json({message:'Internship not found.'}); db.prepare("UPDATE internships SET title=?,description=?,location=?,work_mode=?,duration_weeks=?,stipend=?,skills=?,eligibility_criteria=?,application_deadline=?,status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(input.title,input.description,input.location,input.workMode,input.durationWeeks,input.stipend??null,input.skills,input.eligibilityCriteria,input.applicationDeadline??null,input.status==='DRAFT'?'DRAFT':'PENDING_APPROVAL',internshipId); res.json({message:'Internship updated and submitted for approval.'}) }catch(e){next(e)} })
router.patch('/internships/:internshipId/publish',(req,res,next)=>{try{const p=profile(req.user.id),internshipId=id.parse(req.params.internshipId);const r=db.prepare("UPDATE internships SET status='PENDING_APPROVAL',updated_at=CURRENT_TIMESTAMP WHERE id=? AND industry_id=? AND status IN ('DRAFT','REJECTED')").run(internshipId,p.id);if(!r.changes)return res.status(400).json({message:'Only drafts or rejected postings can be submitted for approval.'});res.json({message:'Internship submitted for approval.'})}catch(e){next(e)}})
router.patch('/internships/:internshipId/unpublish',(req,res,next)=>{try{const p=profile(req.user.id),internshipId=id.parse(req.params.internshipId);const r=db.prepare("UPDATE internships SET status='DRAFT',updated_at=CURRENT_TIMESTAMP WHERE id=? AND industry_id=? AND status='PUBLISHED'").run(internshipId,p.id);if(!r.changes)return res.status(400).json({message:'Only published internships can be unpublished.'});res.json({message:'Internship unpublished.'})}catch(e){next(e)}})
router.delete('/internships/:internshipId',(req,res,next)=>{try{const internshipId=id.parse(req.params.internshipId);const p=profile(req.user.id);const r=db.prepare('DELETE FROM internships WHERE id=? AND industry_id=?').run(internshipId,p.id);if(!r.changes)return res.status(404).json({message:'Internship not found.'});res.status(204).send()}catch(e){next(e)}})
router.get('/applications',(req,res)=>{const p=profile(req.user.id);const rows=db.prepare(`SELECT a.*,i.id internship_id,i.title,u.name student_name,u.email student_email,sp.student_id,sp.college_name,sp.course,sp.skills student_skills FROM applications a JOIN internships i ON i.id=a.internship_id JOIN student_profiles sp ON sp.id=a.student_id JOIN users u ON u.id=sp.user_id WHERE i.industry_id=? ORDER BY a.applied_at DESC`).all(p.id);res.json({applications:rows.map(r=>({id:r.id,status:r.status,coverLetter:r.cover_letter,appliedAt:r.applied_at,internship:{id:r.internship_id,title:r.title},student:{name:r.student_name,email:r.student_email,studentId:r.student_id,collegeName:r.college_name,course:r.course,skills:r.student_skills}}))})})
router.get('/applications/:applicationId',(req,res,next)=>{try{const p=profile(req.user.id),applicationId=id.parse(req.params.applicationId);const row=db.prepare(`SELECT a.*,i.title,u.name,u.email,sp.id profile_id,sp.student_id,sp.college_name,sp.course,sp.graduation_year,sp.skills,sp.bio,sp.phone,sp.resume_url FROM applications a JOIN internships i ON i.id=a.internship_id JOIN industry_profiles ip ON ip.id=i.industry_id JOIN student_profiles sp ON sp.id=a.student_id JOIN users u ON u.id=sp.user_id WHERE a.id=? AND ip.id=?`).get(applicationId,p.id);if(!row)return res.status(404).json({message:'Application not found.'});const records=db.prepare('SELECT * FROM academic_records WHERE student_id=?').all(row.profile_id);const skills=db.prepare('SELECT name,proficiency FROM student_skills WHERE student_id=?').all(row.profile_id);res.json({application:row,student:{name:row.name,email:row.email,studentId:row.student_id,collegeName:row.college_name,course:row.course,graduationYear:row.graduation_year,skills:row.skills,bio:row.bio,phone:row.phone,resumeUrl:row.resume_url,academicRecords:records,normalizedSkills:skills}})}catch(e){next(e)}})
router.patch('/applications/:applicationId/status',(req,res,next)=>{try{const applicationId=id.parse(req.params.applicationId);const {status}=statusSchema.parse(req.body);const p=profile(req.user.id);const r=db.prepare('UPDATE applications SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND internship_id IN (SELECT id FROM internships WHERE industry_id=?)').run(status,applicationId,p.id);if(!r.changes)return res.status(404).json({message:'Application not found.'});res.json({message:'Application status updated.',status})}catch(e){next(e)}})
router.patch('/applications/:applicationId/interview',(req,res,next)=>{try{const p=profile(req.user.id),applicationId=id.parse(req.params.applicationId),v=interviewSchema.parse(req.body);const r=db.prepare('UPDATE applications SET interview_at=?,interview_notes=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND internship_id IN (SELECT id FROM internships WHERE industry_id=?)').run(v.interviewAt??null,v.interviewNotes,applicationId,p.id);if(!r.changes)return res.status(404).json({message:'Application not found.'});res.json({message:'Interview information saved.'})}catch(e){next(e)}})
router.patch('/applications/:applicationId/offer',(req,res,next)=>{try{const p=profile(req.user.id),applicationId=id.parse(req.params.applicationId),v=offerSchema.parse(req.body);const r=db.prepare("UPDATE applications SET offer_details=?,offer_status='OFFERED',status='SELECTED',updated_at=CURRENT_TIMESTAMP WHERE id=? AND internship_id IN (SELECT id FROM internships WHERE industry_id=?)").run(v.offerDetails,applicationId,p.id);if(!r.changes)return res.status(404).json({message:'Application not found.'});res.json({message:'Offer sent.'})}catch(e){next(e)}})
router.patch('/applications/:applicationId/completion',(req,res,next)=>{try{const p=profile(req.user.id),applicationId=id.parse(req.params.applicationId),v=completionSchema.parse(req.body);const r=db.prepare('UPDATE applications SET completion_status=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND offer_status=\'ACCEPTED\' AND internship_id IN (SELECT id FROM internships WHERE industry_id=?)').run(v.completionStatus,applicationId,p.id);if(!r.changes)return res.status(400).json({message:'Only an accepted offer can move into progress or be completed.'});res.json({message:'Completion status saved.'})}catch(e){next(e)}})
router.get('/dashboard',(req,res)=>{const p=profile(req.user.id);const count=(where='1=1')=>db.prepare(`SELECT COUNT(*) count FROM internships WHERE industry_id=? AND ${where}`).get(p.id).count;const applications=db.prepare('SELECT COUNT(*) count FROM applications a JOIN internships i ON i.id=a.internship_id WHERE i.industry_id=?').get(p.id).count;const appCount=(where)=>db.prepare(`SELECT COUNT(*) count FROM applications a JOIN internships i ON i.id=a.internship_id WHERE i.industry_id=? AND ${where}`).get(p.id).count;res.json({profile:{companyName:p.company_name,website:p.website,location:p.location,description:p.description},counts:{totalInternships:count(),activeInternships:count("status='PUBLISHED'"),applicationsReceived:applications,pendingApplications:appCount("a.status='PENDING'"),shortlistedCandidates:appCount("a.status='SHORTLISTED'"),internshipsInProgress:appCount("a.completion_status='IN_PROGRESS'"),completedInternships:appCount("a.completion_status='COMPLETED'")}})})
export default router
