import { Router } from 'express'
import { z } from 'zod'
import { prisma } from '../lib/prisma.js'
import { authenticate, authorize } from '../middleware/authenticate.js'
import { certificateIdentifier, certificateQrPayload } from '../utils/identifiers.js'
import { internshipSummary } from '../utils/serializers.js'

const router = Router(); router.use(authenticate, authorize('COMPANY'))
const id = z.coerce.number().int().positive()
const profileSchema = z.object({ companyName: z.string().trim().min(2).max(150).optional(), website: z.string().trim().url().max(2048).nullable().optional(), location: z.string().trim().max(150).nullable().optional(), description: z.string().trim().max(2000).optional() }).refine((value) => Object.keys(value).length > 0, 'Provide at least one profile field to update.')
const internshipSchema = z.object({ title: z.string().trim().min(3).max(150), description: z.string().trim().min(20).max(5000), location: z.string().trim().min(2).max(150), workMode: z.enum(['REMOTE', 'ONSITE', 'HYBRID']), durationWeeks: z.coerce.number().int().min(1).max(104), stipend: z.coerce.number().int().min(0).max(10000000).nullable().optional(), skills: z.string().trim().max(1000).optional().default(''), eligibilityCriteria: z.string().trim().max(3000).optional().default(''), applicationDeadline: z.string().datetime().nullable().optional(), startDate: z.string().datetime().nullable().optional(), endDate: z.string().datetime().nullable().optional(), status: z.enum(['DRAFT', 'OPEN', 'CLOSED']).optional().default('DRAFT') })
const applicationStatusSchema = z.object({ status: z.enum(['SHORTLISTED', 'SELECTED', 'REJECTED']) })
const progressSchema = z.object({ progressPercent: z.coerce.number().int().min(0).max(100), note: z.string().trim().max(2000).optional().default('') })
const evaluationSchema = z.object({ rating: z.coerce.number().int().min(1).max(5), feedback: z.string().trim().min(3).max(3000) })
const submissionSchema = z.object({ approve: z.boolean().default(true), note: z.string().trim().max(1000).optional() })

async function company(userId) { const profile = await prisma.companyProfile.findUnique({ where: { userId } }); if (!profile) { const error = new Error('Company profile was not found.'); error.status = 404; throw error } return profile }
async function ownedApplication(companyId, applicationId) { return prisma.application.findFirst({ where: { id: applicationId, internship: { companyId } }, include: { student: { include: { user: true, academicRecords: true, skills: true } }, internship: true, progressUpdates: { orderBy: { recordedAt: 'desc' } }, certificate: true, evaluation: true } }) }
function dates(input) { return { applicationDeadline: input.applicationDeadline ? new Date(input.applicationDeadline) : null, startDate: input.startDate ? new Date(input.startDate) : null, endDate: input.endDate ? new Date(input.endDate) : null } }

router.get('/profile', async (req, res, next) => { try { const p = await company(req.user.id); res.json({ profile: { companyName: p.companyName, website: p.website, location: p.location, description: p.description, isVerified: p.isVerified, isSuspicious: p.isSuspicious } }) } catch (error) { next(error) } })
router.patch('/profile', async (req, res, next) => { try { const p = await company(req.user.id); const input = profileSchema.parse(req.body); const profile = await prisma.companyProfile.update({ where: { id: p.id }, data: input }); res.json({ message: 'Company profile updated.', profile }) } catch (error) { next(error) } })
router.post('/internships', async (req, res, next) => { try { const p = await company(req.user.id); const input = internshipSchema.parse(req.body); const internship = await prisma.internship.create({ data: { companyId: p.id, title: input.title, description: input.description, location: input.location, workMode: input.workMode, durationWeeks: input.durationWeeks, stipend: input.stipend, requiredSkills: input.skills, eligibilityCriteria: input.eligibilityCriteria, status: input.status, ...dates(input) } }); res.status(201).json({ message: 'Internship created.', internship }) } catch (error) { next(error) } })
router.get('/internships', async (req, res, next) => { try { const p = await company(req.user.id); const internships = await prisma.internship.findMany({ where: { companyId: p.id }, include: { company: true }, orderBy: { createdAt: 'desc' } }); res.json({ internships: internships.map(internshipSummary) }) } catch (error) { next(error) } })
router.patch('/internships/:internshipId', async (req, res, next) => { try { const p = await company(req.user.id); const input = internshipSchema.parse(req.body); const internshipId = id.parse(req.params.internshipId); const found = await prisma.internship.findFirst({ where: { id: internshipId, companyId: p.id } }); if (!found) return res.status(404).json({ message: 'Internship not found.' }); const internship = await prisma.internship.update({ where: { id: internshipId }, data: { title: input.title, description: input.description, location: input.location, workMode: input.workMode, durationWeeks: input.durationWeeks, stipend: input.stipend, requiredSkills: input.skills, eligibilityCriteria: input.eligibilityCriteria, status: input.status, ...dates(input) } }); res.json({ message: 'Internship updated.', internship }) } catch (error) { next(error) } })
router.patch('/internships/:internshipId/status', async (req, res, next) => { try { const p = await company(req.user.id); const status = z.object({ status: z.enum(['DRAFT', 'OPEN', 'CLOSED']) }).parse(req.body).status; const internship = await prisma.internship.updateMany({ where: { id: id.parse(req.params.internshipId), companyId: p.id }, data: { status } }); if (!internship.count) return res.status(404).json({ message: 'Internship not found.' }); res.json({ message: `Internship marked ${status}.` }) } catch (error) { next(error) } })
router.delete('/internships/:internshipId', async (req, res, next) => { try { const p = await company(req.user.id); const deleted = await prisma.internship.deleteMany({ where: { id: id.parse(req.params.internshipId), companyId: p.id } }); if (!deleted.count) return res.status(404).json({ message: 'Internship not found.' }); res.status(204).send() } catch (error) { next(error) } })
router.patch('/internships/:internshipId/publish', async (req, res, next) => { try { const p = await company(req.user.id); const updated = await prisma.internship.updateMany({ where: { id: id.parse(req.params.internshipId), companyId: p.id, status: { in: ['DRAFT', 'CLOSED'] } }, data: { status: 'OPEN' } }); if (!updated.count) return res.status(400).json({ message: 'Only a draft or closed internship can be opened.' }); res.json({ message: 'Internship is open for applications.' }) } catch (error) { next(error) } })
router.patch('/internships/:internshipId/unpublish', async (req, res, next) => { try { const p = await company(req.user.id); const updated = await prisma.internship.updateMany({ where: { id: id.parse(req.params.internshipId), companyId: p.id, status: 'OPEN' }, data: { status: 'CLOSED' } }); if (!updated.count) return res.status(400).json({ message: 'Only an open internship can be closed.' }); res.json({ message: 'Internship closed.' }) } catch (error) { next(error) } })
router.get('/applications', async (req, res, next) => { try { const p = await company(req.user.id); const applications = await prisma.application.findMany({ where: { internship: { companyId: p.id } }, include: { internship: true, student: { include: { user: true, skills: true } } }, orderBy: { createdAt: 'desc' } }); res.json({ applications: applications.map((a) => ({ ...a, internship: { id: a.internship.id, title: a.internship.title }, student: { name: a.student.user.name, email: a.student.user.email, studentId: a.student.studentId, collegeName: a.student.collegeName, course: a.student.course, skills: a.student.skills.map((skill) => skill.name).join(', ') } })) }) } catch (error) { next(error) } })
router.get('/applications/:applicationId', async (req, res, next) => { try { const app = await ownedApplication((await company(req.user.id)).id, id.parse(req.params.applicationId)); if (!app) return res.status(404).json({ message: 'Application not found.' }); res.json({ application: app, student: { name: app.student.user.name, email: app.student.user.email, studentId: app.student.studentId, collegeName: app.student.collegeName, course: app.student.course, academicRecords: app.student.academicRecords, skills: app.student.skills } }) } catch (error) { next(error) } })
router.patch('/applications/:applicationId/status', async (req, res, next) => { try { const p = await company(req.user.id); const applicationId = id.parse(req.params.applicationId); const status = applicationStatusSchema.parse(req.body).status; if (!(await ownedApplication(p.id, applicationId))) return res.status(404).json({ message: 'Application not found.' }); const data = { status }; if (status === 'SELECTED') { data.completionStatus = 'NOT_STARTED' } await prisma.application.update({ where: { id: applicationId }, data }); res.json({ message: 'Application status updated.', status }) } catch (error) { next(error) } })
router.patch('/applications/:applicationId/interview', async (req, res, next) => { try { const p = await company(req.user.id); const applicationId = id.parse(req.params.applicationId); const input = z.object({ interviewAt: z.string().datetime().nullable().optional(), interviewNotes: z.string().trim().max(3000).optional().default('') }).parse(req.body); if (!(await ownedApplication(p.id, applicationId))) return res.status(404).json({ message: 'Application not found.' }); await prisma.application.update({ where: { id: applicationId }, data: { interviewAt: input.interviewAt ? new Date(input.interviewAt) : null, interviewNotes: input.interviewNotes } }); res.json({ message: 'Interview information saved.' }) } catch (error) { next(error) } })
router.patch('/applications/:applicationId/offer', async (req, res, next) => { try { const p = await company(req.user.id); const applicationId = id.parse(req.params.applicationId); const { offerDetails } = z.object({ offerDetails: z.string().trim().min(3).max(3000) }).parse(req.body); if (!(await ownedApplication(p.id, applicationId))) return res.status(404).json({ message: 'Application not found.' }); await prisma.application.update({ where: { id: applicationId }, data: { offerDetails, status: 'SELECTED' } }); res.json({ message: 'Offer sent.' }) } catch (error) { next(error) } })
router.post('/applications/:applicationId/progress', async (req, res, next) => { try { const p = await company(req.user.id); const applicationId = id.parse(req.params.applicationId); const input = progressSchema.parse(req.body); if (!(await ownedApplication(p.id, applicationId))) return res.status(404).json({ message: 'Application not found.' }); const update = await prisma.internshipProgress.create({ data: { applicationId, ...input, recordedByUserId: req.user.id } }); res.status(201).json({ message: 'Progress recorded.', progress: update }) } catch (error) { next(error) } })
router.put('/applications/:applicationId/evaluation', async (req, res, next) => { try { const p = await company(req.user.id); const applicationId = id.parse(req.params.applicationId); const input = evaluationSchema.parse(req.body); if (!(await ownedApplication(p.id, applicationId))) return res.status(404).json({ message: 'Application not found.' }); const evaluation = await prisma.evaluation.upsert({ where: { applicationId }, update: { ...input, evaluatorUserId: req.user.id }, create: { applicationId, ...input, evaluatorUserId: req.user.id } }); res.json({ message: 'Evaluation saved.', evaluation }) } catch (error) { next(error) } })
router.patch('/applications/:applicationId/completion', async (req, res, next) => { try { const p = await company(req.user.id); const applicationId = id.parse(req.params.applicationId); const completionStatus = z.object({ completionStatus: z.enum(['IN_PROGRESS', 'COMPLETED']) }).parse(req.body).completionStatus; const app = await ownedApplication(p.id, applicationId); if (!app || app.status !== 'SELECTED') return res.status(400).json({ message: 'Only a selected application can be started or completed.' }); const application = await prisma.application.update({ where: { id: applicationId }, data: { completionStatus, startedAt: completionStatus === 'IN_PROGRESS' ? new Date() : app.startedAt, completedAt: completionStatus === 'COMPLETED' ? new Date() : null } }); res.json({ message: 'Completion status saved.', application }) } catch (error) { next(error) } })
router.post('/applications/:applicationId/certificate', async (req, res, next) => { try { const p = await company(req.user.id); const applicationId = id.parse(req.params.applicationId); const input = submissionSchema.parse(req.body); const app = await ownedApplication(p.id, applicationId); if (!app || app.completionStatus !== 'COMPLETED') return res.status(400).json({ message: 'Only a completed internship can have a certificate approved.' }); if (!input.approve) { await prisma.application.update({ where: { id: applicationId }, data: { certificateSubmissionStatus: 'REJECTED' } }); return res.json({ message: 'Certificate submission rejected.' }) }; if (app.certificate) return res.json({ message: 'Certificate already approved.', certificate: app.certificate }); const certificateCode = certificateIdentifier(); const certificate = await prisma.$transaction(async (tx) => { await tx.application.update({ where: { id: applicationId }, data: { certificateSubmissionStatus: 'APPROVED' } }); return tx.certificate.create({ data: { certificateCode, qrPayload: certificateQrPayload(certificateCode), applicationId, issuedByUserId: req.user.id, title: 'Internship Completion Certificate' } }) }); res.status(201).json({ message: 'Certificate approved.', certificate }) } catch (error) { next(error) } })
router.get('/dashboard', async (req, res, next) => { try { const p = await company(req.user.id); const [totalInternships, activeInternships, applicationsReceived, selectedStudents, inProgress, completed] = await prisma.$transaction([prisma.internship.count({ where: { companyId: p.id } }), prisma.internship.count({ where: { companyId: p.id, status: 'OPEN' } }), prisma.application.count({ where: { internship: { companyId: p.id } } }), prisma.application.count({ where: { internship: { companyId: p.id }, status: 'SELECTED' } }), prisma.application.count({ where: { internship: { companyId: p.id }, completionStatus: 'IN_PROGRESS' } }), prisma.application.count({ where: { internship: { companyId: p.id }, completionStatus: 'COMPLETED' } })]); res.json({ counts: { totalInternships, activeInternships, applicationsReceived, selectedStudents, internshipsInProgress: inProgress, completedInternships: completed } }) } catch (error) { next(error) } })

export default router
