import { Router } from 'express'
import { z } from 'zod'
import { prisma } from '../lib/prisma.js'
import { authenticate, authorize } from '../middleware/authenticate.js'

const router = Router(); router.use(authenticate)
const id = z.coerce.number().int().positive()
const academicSchema = z.object({ institution: z.string().trim().min(2).max(150), qualification: z.string().trim().min(2).max(150), fieldOfStudy: z.string().trim().max(150).nullable().optional(), startYear: z.coerce.number().int().min(1950).max(2100).nullable().optional(), endYear: z.coerce.number().int().min(1950).max(2100).nullable().optional(), grade: z.string().trim().max(30).nullable().optional() })
const skillSchema = z.object({ name: z.string().trim().min(1).max(80), proficiency: z.enum(['BEGINNER', 'INTERMEDIATE', 'ADVANCED']).default('BEGINNER') })
const progressSchema = z.object({ progressPercent: z.coerce.number().int().min(0).max(100), note: z.string().trim().max(2000).optional().default('') })
const submissionSchema = z.object({ reportUrl: z.string().trim().url().max(2048).nullable().optional(), certificateFileUrl: z.string().trim().url().max(2048).nullable().optional() }).refine((value) => value.reportUrl || value.certificateFileUrl, 'Provide a report or certificate URL.')
async function student(userId) { const profile = await prisma.studentProfile.findUnique({ where: { userId } }); if (!profile) { const error = new Error('Student profile was not found.'); error.status = 404; throw error } return profile }

router.get('/students/academic-records', authorize('STUDENT'), async (req, res, next) => { try { const records = await prisma.academicRecord.findMany({ where: { student: { userId: req.user.id } }, orderBy: { endYear: 'desc' } }); res.json({ records }) } catch (error) { next(error) } })
router.post('/students/academic-records', authorize('STUDENT'), async (req, res, next) => { try { const record = await prisma.academicRecord.create({ data: { ...academicSchema.parse(req.body), studentId: (await student(req.user.id)).id } }); res.status(201).json({ record }) } catch (error) { next(error) } })
router.patch('/students/academic-records/:recordId', authorize('STUDENT'), async (req, res, next) => { try { const record = await prisma.academicRecord.updateMany({ where: { id: id.parse(req.params.recordId), student: { userId: req.user.id } }, data: academicSchema.parse(req.body) }); if (!record.count) return res.status(404).json({ message: 'Academic record not found.' }); res.json({ message: 'Academic record updated.' }) } catch (error) { next(error) } })
router.delete('/students/academic-records/:recordId', authorize('STUDENT'), async (req, res, next) => { try { const record = await prisma.academicRecord.deleteMany({ where: { id: id.parse(req.params.recordId), student: { userId: req.user.id } } }); if (!record.count) return res.status(404).json({ message: 'Academic record not found.' }); res.status(204).send() } catch (error) { next(error) } })
router.get('/students/skills', authorize('STUDENT'), async (req, res, next) => { try { const skills = await prisma.studentSkill.findMany({ where: { student: { userId: req.user.id } }, orderBy: { name: 'asc' } }); res.json({ skills }) } catch (error) { next(error) } })
router.post('/students/skills', authorize('STUDENT'), async (req, res, next) => { try { const skill = await prisma.studentSkill.create({ data: { ...skillSchema.parse(req.body), studentId: (await student(req.user.id)).id } }); res.status(201).json({ skill }) } catch (error) { next(error) } })
router.delete('/students/skills/:skillId', authorize('STUDENT'), async (req, res, next) => { try { const skill = await prisma.studentSkill.deleteMany({ where: { id: id.parse(req.params.skillId), student: { userId: req.user.id } } }); if (!skill.count) return res.status(404).json({ message: 'Skill not found.' }); res.status(204).send() } catch (error) { next(error) } })
router.get('/students/applications/:applicationId/progress', authorize('STUDENT'), async (req, res, next) => { try { const application = await prisma.application.findFirst({ where: { id: id.parse(req.params.applicationId), student: { userId: req.user.id } }, include: { progressUpdates: { orderBy: { recordedAt: 'desc' } } } }); if (!application) return res.status(404).json({ message: 'Application not found.' }); res.json({ progress: application.progressUpdates }) } catch (error) { next(error) } })
router.post('/students/applications/:applicationId/progress', authorize('STUDENT'), async (req, res, next) => { try { const applicationId = id.parse(req.params.applicationId); const application = await prisma.application.findFirst({ where: { id: applicationId, student: { userId: req.user.id }, completionStatus: 'IN_PROGRESS' } }); if (!application) return res.status(400).json({ message: 'Only your active internship can receive progress updates.' }); const progress = await prisma.internshipProgress.create({ data: { applicationId, ...progressSchema.parse(req.body), recordedByUserId: req.user.id } }); res.status(201).json({ progress }) } catch (error) { next(error) } })
router.post('/students/applications/:applicationId/submission', authorize('STUDENT'), async (req, res, next) => { try { const applicationId = id.parse(req.params.applicationId); const application = await prisma.application.findFirst({ where: { id: applicationId, student: { userId: req.user.id }, completionStatus: 'COMPLETED' } }); if (!application) return res.status(400).json({ message: 'Only your completed internship can receive a report or certificate submission.' }); const submitted = await prisma.application.update({ where: { id: applicationId }, data: { ...submissionSchema.parse(req.body), certificateSubmissionStatus: 'SUBMITTED' } }); res.json({ message: 'Submission sent to the company for approval.', application: submitted }) } catch (error) { next(error) } })
router.get('/students/certificates', authorize('STUDENT'), async (req, res, next) => { try { const certificates = await prisma.certificate.findMany({ where: { application: { student: { userId: req.user.id } } }, include: { application: { include: { internship: true } } }, orderBy: { issuedAt: 'desc' } }); res.json({ certificates }) } catch (error) { next(error) } })

export default router
