import { Router } from 'express'
import crypto from 'node:crypto'
import { z } from 'zod'
import { db } from '../database.js'
import { authenticate, authorize } from '../middleware/authenticate.js'

const router = Router(); router.use(authenticate)
const id = z.coerce.number().int().positive()
const academic = z.object({ institution:z.string().trim().min(2).max(150), qualification:z.string().trim().min(2).max(150), fieldOfStudy:z.string().trim().max(150).nullable().optional(), startYear:z.coerce.number().int().min(1950).max(2100).nullable().optional(), endYear:z.coerce.number().int().min(1950).max(2100).nullable().optional(), grade:z.string().trim().max(30).nullable().optional() })
const skills=z.object({name:z.string().trim().min(1).max(80),proficiency:z.enum(['BEGINNER','INTERMEDIATE','ADVANCED']).default('BEGINNER')})
const progress=z.object({progressPercent:z.coerce.number().int().min(0).max(100),note:z.string().trim().max(2000).optional().default('')})
const evaluation=z.object({rating:z.coerce.number().int().min(1).max(5),feedback:z.string().trim().min(3).max(3000)})
const studentId=(userId)=>db.prepare('SELECT id FROM student_profiles WHERE user_id=?').get(userId).id
const ownsApplication=(userId,applicationId)=>db.prepare('SELECT a.id FROM applications a JOIN internships i ON i.id=a.internship_id JOIN industry_profiles ip ON ip.id=i.industry_id WHERE a.id=? AND ip.user_id=?').get(applicationId,userId)

router.get('/students/academic-records',authorize('STUDENT'),(req,res)=>res.json({records:db.prepare('SELECT * FROM academic_records WHERE student_id=? ORDER BY end_year DESC').all(studentId(req.user.id))}))
router.post('/students/academic-records',authorize('STUDENT'),(req,res,next)=>{try{const v=academic.parse(req.body);const r=db.prepare('INSERT INTO academic_records (student_id,institution,qualification,field_of_study,start_year,end_year,grade) VALUES (?,?,?,?,?,?,?)').run(studentId(req.user.id),v.institution,v.qualification,v.fieldOfStudy??null,v.startYear??null,v.endYear??null,v.grade??null);res.status(201).json({id:Number(r.lastInsertRowid),...v})}catch(e){next(e)}})
router.patch('/students/academic-records/:recordId',authorize('STUDENT'),(req,res,next)=>{try{const v=academic.parse(req.body),recordId=id.parse(req.params.recordId);const r=db.prepare('UPDATE academic_records SET institution=?,qualification=?,field_of_study=?,start_year=?,end_year=?,grade=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND student_id=?').run(v.institution,v.qualification,v.fieldOfStudy??null,v.startYear??null,v.endYear??null,v.grade??null,recordId,studentId(req.user.id));if(!r.changes)return res.status(404).json({message:'Academic record not found.'});res.json({message:'Academic record updated.'})}catch(e){next(e)}})
router.delete('/students/academic-records/:recordId',authorize('STUDENT'),(req,res,next)=>{try{const r=db.prepare('DELETE FROM academic_records WHERE id=? AND student_id=?').run(id.parse(req.params.recordId),studentId(req.user.id));if(!r.changes)return res.status(404).json({message:'Academic record not found.'});res.status(204).send()}catch(e){next(e)}})
router.get('/students/skills',authorize('STUDENT'),(req,res)=>res.json({skills:db.prepare('SELECT * FROM student_skills WHERE student_id=? ORDER BY name').all(studentId(req.user.id))}))
router.post('/students/skills',authorize('STUDENT'),(req,res,next)=>{try{const v=skills.parse(req.body);const r=db.prepare('INSERT INTO student_skills (student_id,name,proficiency) VALUES (?,?,?)').run(studentId(req.user.id),v.name,v.proficiency);res.status(201).json({id:Number(r.lastInsertRowid),...v})}catch(e){next(e)}})
router.delete('/students/skills/:skillId',authorize('STUDENT'),(req,res,next)=>{try{const r=db.prepare('DELETE FROM student_skills WHERE id=? AND student_id=?').run(id.parse(req.params.skillId),studentId(req.user.id));if(!r.changes)return res.status(404).json({message:'Skill not found.'});res.status(204).send()}catch(e){next(e)}})
router.get('/students/applications/:applicationId/progress',authorize('STUDENT'),(req,res,next)=>{try{const applicationId=id.parse(req.params.applicationId);const rows=db.prepare('SELECT p.* FROM internship_progress p JOIN applications a ON a.id=p.application_id JOIN student_profiles sp ON sp.id=a.student_id WHERE p.application_id=? AND sp.user_id=? ORDER BY p.recorded_at DESC').all(applicationId,req.user.id);res.json({progress:rows})}catch(e){next(e)}})
router.get('/students/certificates',authorize('STUDENT'),(req,res)=>res.json({certificates:db.prepare('SELECT c.*,i.title internship_title FROM certificates c JOIN applications a ON a.id=c.application_id JOIN student_profiles sp ON sp.id=a.student_id JOIN internships i ON i.id=a.internship_id WHERE sp.user_id=? ORDER BY c.issued_at DESC').all(req.user.id)}))
router.post('/industry/applications/:applicationId/progress',authorize('INDUSTRY'),(req,res,next)=>{try{const applicationId=id.parse(req.params.applicationId),v=progress.parse(req.body);if(!ownsApplication(req.user.id,applicationId))return res.status(404).json({message:'Application not found.'});const r=db.prepare('INSERT INTO internship_progress (application_id,progress_percent,note,recorded_by_user_id) VALUES (?,?,?,?)').run(applicationId,v.progressPercent,v.note,req.user.id);res.status(201).json({id:Number(r.lastInsertRowid),...v})}catch(e){next(e)}})
router.put('/industry/applications/:applicationId/evaluation',authorize('INDUSTRY'),(req,res,next)=>{try{const applicationId=id.parse(req.params.applicationId),v=evaluation.parse(req.body);if(!ownsApplication(req.user.id,applicationId))return res.status(404).json({message:'Application not found.'});db.prepare('INSERT INTO evaluations (application_id,rating,feedback,evaluator_user_id) VALUES (?,?,?,?) ON CONFLICT(application_id) DO UPDATE SET rating=excluded.rating,feedback=excluded.feedback,evaluator_user_id=excluded.evaluator_user_id,updated_at=CURRENT_TIMESTAMP').run(applicationId,v.rating,v.feedback,req.user.id);res.json({message:'Evaluation saved.',...v})}catch(e){next(e)}})
router.post('/industry/applications/:applicationId/certificate',authorize('INDUSTRY'),(req,res,next)=>{try{const applicationId=id.parse(req.params.applicationId);const app=db.prepare("SELECT a.id FROM applications a JOIN internships i ON i.id=a.internship_id JOIN industry_profiles ip ON ip.id=i.industry_id WHERE a.id=? AND ip.user_id=? AND a.status='SELECTED'").get(applicationId,req.user.id);if(!app)return res.status(400).json({message:'A certificate can only be issued for your selected applicant.'});const code=`IX-${crypto.randomUUID().slice(0,8).toUpperCase()}`;const r=db.prepare('INSERT INTO certificates (certificate_code,application_id,issued_by_user_id,title) VALUES (?,?,?,?)').run(code,applicationId,req.user.id,'Internship Completion Certificate');const certificateId=Number(r.lastInsertRowid);db.prepare("INSERT INTO certificate_verifications (certificate_id,verification_status,note) VALUES (?,'VALID','Issued')").run(certificateId);res.status(201).json({id:certificateId,certificateCode:code})}catch(e){next(e)}})
export default router
