import { ArrowRight, Building2, Eye, EyeOff, GraduationCap, ShieldCheck, Users } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { useState } from 'react'
import { useAuth } from '../context/AuthContext'
import './auth-register.css'

const roles = [
  ['STUDENT', 'Student', GraduationCap, 'Build your verified career journey'],
  ['FACULTY', 'Faculty', Users, 'Guide outcomes with confidence'],
  ['COMPANY', 'Company', Building2, 'Find verified talent, faster'],
]
const destination = (user) => `/${user.role.toLowerCase()}/dashboard`

export function AuthPage() {
  const { login } = useAuth(); const nav = useNavigate(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [show, setShow] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState('')
  const submit = async (event) => { event.preventDefault(); setLoading(true); setError(''); try { nav(destination(await login(email, password))) } catch (err) { setError(err.message) } finally { setLoading(false) } }
  return <div className="auth-page"><section className="auth-brand"><div className="wordmark"><i>IX</i><span>Intern<em>X</em></span></div><div><p className="eyebrow">VERIFIED INTERNSHIP ECOSYSTEM</p><h1>Careers, with<br /><em>clarity.</em></h1><p>One trusted platform connecting students, institutions, and companies through every internship milestone.</p></div><div className="auth-proof"><ShieldCheck /><div><b>Built on verified records</b><span>Identity, progress and credentials in one place.</span></div></div></section><section className="auth-form-wrap"><form className="auth-card" onSubmit={submit}><p className="eyebrow">WELCOME TO INTERNX</p><h2>Sign in to your workspace</h2><p className="subtle">Use your registered InternX account to continue.</p><label>Email<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@example.edu" required /></label><label>Password<div className="password-field"><input type={show ? 'text' : 'password'} value={password} onChange={(event) => setPassword(event.target.value)} required /><button type="button" aria-label="Toggle password visibility" onClick={() => setShow(!show)}>{show ? <EyeOff size={18} /> : <Eye size={18} />}</button></div></label>{error && <p className="auth-error" role="alert">{error}</p>}<button className="primary-btn" disabled={loading}>{loading ? 'Signing in…' : 'Sign in'}<ArrowRight size={18} /></button><div className="auth-links"><Link to="/forgot-password">Forgot password?</Link><Link to="/register">Create account</Link></div></form></section></div>
}

export function RegisterPage() {
  const { register } = useAuth(); const nav = useNavigate(); const [form, setForm] = useState({ name: '', email: '', password: '', role: 'STUDENT', companyName: '', institution: '' }); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  const set = (key) => (event) => setForm({ ...form, [key]: event.target.value })
  const submit = async (event) => { event.preventDefault(); setError(''); setLoading(true); const { companyName, institution, ...base } = form; const payload = form.role === 'COMPANY' ? { ...base, companyName } : form.role === 'FACULTY' ? { ...base, institution } : base; try { nav(destination(await register(payload))) } catch (err) { setError(err.message) } finally { setLoading(false) } }
  return <div className="simple-auth"><Link className="wordmark" to="/login"><i>IX</i><span>Intern<em>X</em></span></Link><form className="auth-card" onSubmit={submit}><p className="eyebrow">INTERNX ACCESS</p><h2>Create your account</h2><p className="subtle">Start with the essentials. You can complete and edit your profile later.</p><label>Full name<input value={form.name} onChange={set('name')} required /></label><label>Email<input type="email" value={form.email} onChange={set('email')} required /></label><label>Password<input type="password" value={form.password} onChange={set('password')} minLength="8" required /><small>At least 8 characters, including uppercase, lowercase, and a number.</small></label><fieldset className="role-picker"><legend>Account type</legend>{roles.map(([value, label, Icon, detail]) => <label key={value}><input type="radio" name="role" value={value} checked={form.role === value} onChange={set('role')} /><Icon size={19} /><span><b>{label}</b><small>{detail}</small></span></label>)}</fieldset>{form.role === 'COMPANY' && <label>Company name<input value={form.companyName} onChange={set('companyName')} required /></label>}{form.role === 'FACULTY' && <label>Institution<input value={form.institution} onChange={set('institution')} required /></label>}{error && <p className="auth-error" role="alert">{error}</p>}<button className="primary-btn" disabled={loading}>{loading ? 'Creating account…' : 'Create account'}<ArrowRight size={18} /></button><Link className="back-link" to="/login">Back to sign in</Link></form></div>
}

export function ForgotPasswordPage() { return <div className="simple-auth"><Link className="wordmark" to="/login"><i>IX</i><span>Intern<em>X</em></span></Link><section className="auth-card"><p className="eyebrow">ACCOUNT RECOVERY</p><h2>Reset your password</h2><p className="subtle">Contact your institution administrator to reset your InternX account password.</p><Link className="back-link" to="/login">Back to sign in</Link></section></div> }
