import { ArrowRight, Building2, Eye, EyeOff, GraduationCap, ShieldCheck, Users } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { useState } from 'react'
import { useAuth } from '../context/AuthContext'
const roles=[['STUDENT','Student',GraduationCap,'Build your verified career journey'],['FACULTY','Faculty',Users,'Guide outcomes with confidence'],['COMPANY','Company',Building2,'Find verified talent, faster']]
export function AuthPage(){const {login}=useAuth();const nav=useNavigate();const [role,setRole]=useState('STUDENT'),[show,setShow]=useState(false),[loading,setLoading]=useState(false);const submit=e=>{e.preventDefault();setLoading(true);setTimeout(()=>{login(role);nav(`/${role.toLowerCase()}/dashboard`)},450)};return <div className="auth-page"><section className="auth-brand"><div className="wordmark"><i>IX</i><span>Intern<em>X</em></span></div><div><p className="eyebrow">VERIFIED INTERNSHIP ECOSYSTEM</p><h1>Careers, with<br/><em>clarity.</em></h1><p>One trusted platform connecting students, institutions, and companies through every internship milestone.</p></div><div className="auth-proof"><ShieldCheck/><div><b>Built on verified records</b><span>Identity, progress and credentials in one place.</span></div></div></section><section className="auth-form-wrap"><form className="auth-card" onSubmit={submit}><p className="eyebrow">WELCOME TO INTERNX</p><h2>Sign in to your workspace</h2><p className="subtle">Choose your demo workspace to explore the platform.</p><div className="role-picker">{roles.map(([key,label,Icon,detail])=><button type="button" key={key} onClick={()=>setRole(key)} className={role===key?'selected':''}><Icon size={19}/><span><b>{label}</b><small>{detail}</small></span></button>)}</div><label>Email<input type="email" placeholder="you@example.edu" required/></label><label>Password<div className="password-field"><input type={show?'text':'password'} placeholder="Enter your password" required/><button type="button" aria-label="Toggle password visibility" onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label><button className="primary-btn" disabled={loading}>{loading?'Opening workspace…':'Sign in'}<ArrowRight size={18}/></button><div className="auth-links"><Link to="/forgot-password">Forgot password?</Link><Link to="/register">Create account</Link></div></form></section></div>}
export function RegisterPage(){return <SimpleAuth title="Create your InternX account" text="Registration is available for student and company demo workspaces." action="Create demo workspace"/>}
export function ForgotPasswordPage(){return <SimpleAuth title="Reset your password" text="Enter your email and we’ll send a secure reset link." action="Send reset link"/>}
function SimpleAuth({title,text,action}){return <div className="simple-auth"><Link className="wordmark" to="/login"><i>IX</i><span>Intern<em>X</em></span></Link><form className="auth-card"><p className="eyebrow">INTERNX ACCESS</p><h2>{title}</h2><p className="subtle">{text}</p><label>Email<input type="email" placeholder="you@example.edu" required/></label><button className="primary-btn">{action}<ArrowRight size={18}/></button><Link className="back-link" to="/login">Back to sign in</Link></form></div>}
