import { BriefcaseBusiness, FilePlus2, Users } from 'lucide-react'
import { Link, Route, Routes } from 'react-router-dom'
import { useEffect, useState } from 'react'
import { EmptyState, PageHeader, SectionCard, StatCard, StatusBadge } from '../components/common/Ui'
import { getCompanyApplications, getCompanyDashboard, getCompanyInternships, getCompanyProfile, updateCompanyProfile } from '../services/company'
const empty={profile:null,dashboard:null,internships:[],applications:[]}
function useCompanyWorkspace(){const [data,setData]=useState(empty);const [loading,setLoading]=useState(true);const load=()=>Promise.all([getCompanyProfile(),getCompanyDashboard(),getCompanyInternships(),getCompanyApplications()]).then(([p,d,i,a])=>setData({profile:p.profile,dashboard:d.counts,internships:i.internships||[],applications:a.applications||[]})).finally(()=>setLoading(false));useEffect(()=>{load().catch(()=>setData(empty))},[]);return {...data,loading,refresh:load}}
export function CompanyPortal(){const workspace=useCompanyWorkspace();return <Routes><Route path="dashboard" element={<Dashboard {...workspace}/>}/><Route path="profile" element={<Profile {...workspace}/>}/><Route path="internships" element={<Internships {...workspace}/>}/><Route path="applications" element={<Applications {...workspace}/>}/><Route path="*" element={<Dashboard {...workspace}/>}/></Routes>}
function Dashboard({profile,dashboard,applications,internships,loading}){return <><PageHeader eyebrow="COMPANY WORKSPACE" title={loading?'Loading your workspace…':profile?.companyName||'Your company'} description="Only your company’s internships and candidates are visible here." action={<Link className="primary-btn" to="/company/internships"><FilePlus2 size={18}/> Manage internships</Link>}/><div className="stats-grid"><StatCard label="Internships" value={dashboard?.totalInternships||0} detail="Created by your company" icon={BriefcaseBusiness}/><StatCard label="Open internships" value={dashboard?.activeInternships||0} detail="Accepting applications" icon={BriefcaseBusiness}/><StatCard label="Applications" value={dashboard?.applicationsReceived||0} detail="Received by your company" icon={Users}/><StatCard label="Selected candidates" value={dashboard?.selectedStudents||0} detail="Across your roles" icon={Users}/></div><SectionCard title="Recent applications">{applications.length?<div className="application-list">{applications.slice(0,5).map(a=><div key={a.id}><span className="company-mark">{(a.student?.name||'?')[0]}</span><p><b>{a.student?.name}</b><small>{a.internship?.title} · {a.student?.studentId}</small></p><StatusBadge>{a.status}</StatusBadge></div>)}</div>:<EmptyState title="No applications yet" message="Applications to your internships will appear here."/>}</SectionCard><SectionCard title="Your internships">{internships.length?<div className="company-list">{internships.map(i=><article key={i.id}><span className="company-mark">{i.title[0]}</span><p><b>{i.title}</b><small>{i.location} · {i.durationWeeks} weeks</small></p><StatusBadge>{i.status}</StatusBadge></article>)}</div>:<EmptyState title="No internships yet" message="Create your first internship to begin receiving candidates."/>}</SectionCard></>}
function Profile({profile,refresh}){const [form,setForm]=useState({});const [message,setMessage]=useState('');const [saving,setSaving]=useState(false);useEffect(()=>setForm({companyName:profile?.companyName||'',website:profile?.website||'',location:profile?.location||'',description:profile?.description||''}),[profile]);const set=key=>e=>setForm({...form,[key]:e.target.value});const save=async e=>{e.preventDefault();setSaving(true);setMessage('');try{await updateCompanyProfile({...form,website:form.website||null,location:form.location||null});await refresh();setMessage('Profile saved successfully.')}catch(err){setMessage(err.message)}finally{setSaving(false)}};return <><PageHeader eyebrow="COMPANY PROFILE" title="Edit company profile" description="Changes are saved to your company record in InternX."/><SectionCard title="Profile details"><form className="form-grid" onSubmit={save}><label>Company name<input value={form.companyName||''} onChange={set('companyName')} required/></label><label>Website<input type="url" value={form.website||''} onChange={set('website')} placeholder="https://example.com"/></label><label>Location<input value={form.location||''} onChange={set('location')}/></label><label className="full">Description<textarea value={form.description||''} onChange={set('description')}/></label><div className="full">{message&&<p className="auth-error">{message}</p>}<button className="primary-btn" disabled={saving}>{saving?'Saving…':'Save profile'}</button></div></form></SectionCard></>}
function Internships({internships}){return <><PageHeader eyebrow="INTERNSHIPS" title="Your internships" description="Only opportunities created by your company are listed."/>{internships.length?<div className="company-list">{internships.map(i=><article key={i.id}><span className="company-mark">{i.title[0]}</span><p><b>{i.title}</b><small>{i.location} · {i.workMode}</small></p><StatusBadge>{i.status}</StatusBadge></article>)}</div>:<EmptyState title="No internships yet" message="Create an internship to populate this page."/>}</>}
function Applications({applications}){return <><PageHeader eyebrow="APPLICATIONS" title="Candidates for your roles" description="Only candidates who applied to your company are displayed."/>{applications.length?<SectionCard title="Applications"><div className="application-list">{applications.map(a=><div key={a.id}><span className="company-mark">{(a.student?.name||'?')[0]}</span><p><b>{a.student?.name}</b><small>{a.internship?.title} · {a.student?.email}</small></p><StatusBadge>{a.status}</StatusBadge></div>)}</div></SectionCard>:<EmptyState title="No applications yet" message="Candidate applications will appear here."/>}</>}
