import { AlertTriangle, Award, Building2, CheckCircle2, FileCheck2, GraduationCap, ShieldCheck, Users } from 'lucide-react'
import { Link, Route, Routes } from 'react-router-dom'
import { candidates, chartData, student } from '../data/demoData'
import { PageHeader, SearchField, SectionCard, StatCard, StatusBadge } from '../components/common/Ui'
import { Bar, BarChart, ResponsiveContainer, Tooltip, XAxis } from 'recharts'
export function FacultyPortal(){return <Routes><Route path="dashboard" element={<Dashboard/>}/><Route path="students" element={<Students/>}/><Route path="students/:studentId" element={<StudentDetail/>}/><Route path="companies" element={<Companies/>}/><Route path="internships" element={<Internships/>}/><Route path="reports" element={<Reports/>}/><Route path="certificates" element={<Verify/>}/><Route path="certificates/verify" element={<Verify/>}/><Route path="analytics" element={<Analytics/>}/><Route path="placements" element={<Placements/>}/><Route path="settings" element={<Dashboard/>}/><Route path="*" element={<Dashboard/>}/></Routes>}
function Dashboard(){return <><PageHeader eyebrow="FACULTY COMMAND CENTER" title="Institutional internship health" description="Monitor verified student outcomes, company partnerships, and active placements."/><div className="stats-grid"><StatCard label="Total students" value="1,248" detail="Across 6 departments" icon={Users}/><StatCard label="Verified students" value="1,106" detail="88.6% verified" icon={ShieldCheck}/><StatCard label="Active internships" value="286" detail="+18 this month" icon={GraduationCap}/><StatCard label="Certificates issued" value="192" detail="All verifiable" icon={Award}/></div><div className="two-column"><SectionCard title="Internship participation"><div className="chart-wrap"><ResponsiveContainer width="100%" height={220}><BarChart data={chartData}><XAxis dataKey="name"/><Tooltip/><Bar dataKey="value" fill="#5d5feF" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></SectionCard><SectionCard title="Requires attention"><div className="attention-list"><div><AlertTriangle/><p><b>12 reports awaiting review</b><small>Oldest submission: 3 days ago</small></p><Link to="/faculty/reports">Review</Link></div><div><Building2/><p><b>4 companies pending verification</b><small>Documentation submitted</small></p><Link to="/faculty/companies">Review</Link></div><div><FileCheck2/><p><b>7 certificates need confirmation</b><small>Completion records ready</small></p><Link to="/faculty/certificates/verify">Verify</Link></div></div></SectionCard></div></>}
function Students(){return <><PageHeader eyebrow="STUDENT MANAGEMENT" title="Verified student records" description="Search academic identity, internship status, and verification progress." action={<SearchField placeholder="Search by Student ID or name"/>}/><SectionCard title="Students"><div className="data-table"><div className="table-head"><span>Student</span><span>Department</span><span>CGPA</span><span>Internship</span><span>Verification</span></div>{candidates.map(c=><Link to={`/faculty/students/${c.id}`} className="table-row" key={c.id}><span><b>{c.name}</b><small>{c.id}</small></span><span>Data Science</span><span>{c.cgpa}</span><StatusBadge>{c.status}</StatusBadge><StatusBadge>VERIFIED</StatusBadge></Link>)}</div></SectionCard></>}
function StudentDetail(){return <><PageHeader eyebrow="STUDENT PROFILE" title={student.name} description={`${student.id} · ${student.department} · ${student.year}`}/><div className="stats-grid"><StatCard label="CGPA" value={student.cgpa} detail="Academic profile verified" icon={GraduationCap}/><StatCard label="Internship status" value="Active" detail="62% progress" icon={CheckCircle2}/><StatCard label="Risk indicator" value="Low" detail="AI-assisted signal" icon={ShieldCheck}/></div><SectionCard title="Authorized record"><div className="details-list"><div><dt>Current internship</dt><dd>Data Science Intern · Nexora Technologies</dd></div><div><dt>Mentor feedback</dt><dd>Strong analytical ownership and communication.</dd></div><div><dt>Academic status</dt><dd>Verified · No backlogs</dd></div></div></SectionCard></>}
function Companies(){return <><PageHeader eyebrow="COMPANY VERIFICATION" title="Trusted partner companies" description="Verify internship providers before students begin their journey."/><div className="company-list">{[['Nexora Technologies','VERIFIED','18 active internships'],['ABC Technologies','PENDING','Documents under review'],['Quantum Retail','VERIFIED','9 active internships']].map(([name,status,detail])=><article key={name}><span className="company-mark">{name[0]}</span><p><b>{name}</b><small>{detail} · careers@{name.toLowerCase().split(' ')[0]}.com</small></p><StatusBadge>{status}</StatusBadge><button className="outline-btn">View details</button></article>)}</div></>}
function Internships(){return <><PageHeader eyebrow="INTERNSHIP MONITORING" title="Active internship oversight" description="Use verified progress signals to identify where guidance is needed."/><SectionCard title="Internship activity"><div className="data-table"><div className="table-head"><span>Student</span><span>Company</span><span>Progress</span><span>Report</span><span>Risk</span></div>{candidates.map(c=><div className="table-row" key={c.id}><span>{c.name}</span><span>Nexora Technologies</span><span>62%</span><StatusBadge>IN PROGRESS</StatusBadge><StatusBadge>LOW RISK</StatusBadge></div>)}</div></SectionCard></>}
function Reports(){return <><PageHeader eyebrow="REPORT REVIEW" title="Internship reports" description="Approve submissions, request changes, and keep completion records credible."/><SectionCard title="Reports awaiting action"><div className="data-table"><div className="table-head"><span>Student</span><span>Company</span><span>Submitted</span><span>Status</span><span>Action</span></div>{candidates.map(c=><div className="table-row" key={c.id}><span>{c.name}</span><span>Nexora Technologies</span><span>14 Aug 2026</span><StatusBadge>PENDING</StatusBadge><button className="text-link">Review</button></div>)}</div></SectionCard></>}
function Verify(){return <><PageHeader eyebrow="CERTIFICATE VERIFICATION" title="Verify internship certificate" description="Confirm authenticity using the Student ID and Certificate ID." action={<Link className="primary-btn" to="/verify-certificate">Open verifier</Link>}/><section className="verification-callout"><ShieldCheck/><div><h2>Trusted credentials begin with a complete record.</h2><p>Verify student identity, completion, company, and credential before confirming authenticity.</p></div></section></>}
function Analytics(){return <><PageHeader eyebrow="INSTITUTIONAL ANALYTICS" title="Outcomes, made visible" description="Track participation, department distribution, and verified career outcomes."/><Dashboard/></>}
function Placements(){return <><PageHeader eyebrow="PLACEMENT RECORDS" title="Verified placement outcomes" description="A trustworthy record of institutional internship-to-placement journeys."/><SectionCard title="Placement overview"><div className="stats-grid"><StatCard label="Conversion rate" value="38%" detail="Internship to offer"/><StatCard label="Avg. stipend" value="₹16.2k" detail="Per month"/><StatCard label="Verified companies" value="86" detail="Active partners"/></div></SectionCard></>}
