import { Building2, GraduationCap, ShieldCheck, Users } from 'lucide-react'
import { Link, Route, Routes } from 'react-router-dom'
import { useEffect, useState } from 'react'
import { EmptyState, PageHeader, SectionCard, StatCard } from '../components/common/Ui'
import { getFacultyAnalytics, getFacultyProfile, getStudents, updateFacultyProfile } from '../services/faculty'
const empty={profile:null,counts:null,students:[]}
function useFacultyWorkspace(){const [data,setData]=useState(empty);const [loading,setLoading]=useState(true);const load=()=>Promise.all([getFacultyProfile(),getFacultyAnalytics(),getStudents()]).then(([p,a,s])=>setData({profile:p.profile,counts:a.counts,students:s.students||[]})).finally(()=>setLoading(false));useEffect(()=>{load().catch(()=>setData(empty))},[]);return {...data,loading,refresh:load}}
export function FacultyPortal(){const workspace=useFacultyWorkspace();return <Routes><Route path="dashboard" element={<Dashboard {...workspace}/>}/><Route path="students" element={<Students {...workspace}/>}/><Route path="settings" element={<Profile {...workspace}/>}/><Route path="*" element={<Dashboard {...workspace}/>}/></Routes>}
function Dashboard({profile,counts,students,loading}){return <><PageHeader eyebrow="FACULTY WORKSPACE" title={loading?'Loading your workspace…':profile?.institution||'Faculty workspace'} description="Institutional records shown here come from InternX, not demo data."/><div className="stats-grid"><StatCard label="Students" value={counts?.students||0} detail="Registered student profiles" icon={Users}/><StatCard label="Companies" value={counts?.companies||0} detail="Partner company profiles" icon={Building2}/><StatCard label="Open internships" value={counts?.openInternships||0} detail="Available opportunities" icon={GraduationCap}/><StatCard label="Valid certificates" value={counts?.certificates||0} detail="Issued credentials" icon={ShieldCheck}/></div><SectionCard title="Student records">{students.length?<div className="application-list">{students.slice(0,8).map(student=><div key={student.studentId}><span className="company-mark">{student.name[0]}</span><p><b>{student.name}</b><small>{student.studentId} · {student.collegeName||'Institution not added'}</small></p></div>)}</div>:<EmptyState title="No students yet" message="Student accounts will appear here after registration."/>}</SectionCard></>}
function Profile({profile,refresh}){const [form,setForm]=useState({});const [message,setMessage]=useState('');const [saving,setSaving]=useState(false);useEffect(()=>setForm({name:profile?.name||'',institution:profile?.institution||'',department:profile?.department||'',designation:profile?.designation||'',phone:profile?.phone||''}),[profile]);const set=key=>e=>setForm({...form,[key]:e.target.value});const save=async e=>{e.preventDefault();setSaving(true);setMessage('');try{await updateFacultyProfile({...form,institution:form.institution||null,department:form.department||null,designation:form.designation||null,phone:form.phone||null});await refresh();setMessage('Profile saved successfully.')}catch(err){setMessage(err.message)}finally{setSaving(false)}};return <><PageHeader eyebrow="FACULTY PROFILE" title="Edit your profile" description="Changes are saved to your faculty record in InternX."/><SectionCard title="Profile details"><form className="form-grid" onSubmit={save}><label>Full name<input value={form.name||''} onChange={set('name')} required/></label><label>Institution<input value={form.institution||''} onChange={set('institution')}/></label><label>Department<input value={form.department||''} onChange={set('department')}/></label><label>Designation<input value={form.designation||''} onChange={set('designation')}/></label><label>Phone<input value={form.phone||''} onChange={set('phone')}/></label><div className="full">{message&&<p className="auth-error">{message}</p>}<button className="primary-btn" disabled={saving}>{saving?'Saving…':'Save profile'}</button></div></form></SectionCard></>}
function Students({students}){return <><PageHeader eyebrow="STUDENTS" title="Registered student records" description="Institutional student data from the database."/>{students.length?<SectionCard title="Students"><div className="application-list">{students.map(student=><div key={student.studentId}><span className="company-mark">{student.name[0]}</span><p><b>{student.name}</b><small>{student.studentId} · {student.email}</small></p><Link className="text-link" to={`/faculty/students/${student.studentId}`}>View</Link></div>)}</div></SectionCard>:<EmptyState title="No students yet" message="Student accounts will appear here after registration."/>}</>}
